### PR TITLE
Kill the readme

### PR DESCRIPTION
**Pull request by CarlNelson**
**Jira:** FEE-59

**Overview:**
Port readme documentation from ReadME to Dewey

**Screenshots/GIFs:**
Read Me before
e93d18c3c1f222b1a5cc401fa47a32a3

Dewey now
d0943fb842798d0e64e0e71e5b949852

**Testing:**
No tests... just a docs update

**Roll Out:**
- Before merging:
  - [ ] Updated docs
  - [ ] Bumped version in `package.json`
- After merging:
  - [ ] Deployed updated docs (`make deploy-docs`)

### CODE REVIEW

**Comment by osdiab** [comment]
Maybe in the future we can auto generate this stuff from the prop types, but for now this is great.

**Comment by CarlNelson** [comment]
Trust me… I'd love that. I just lived in #propcity for like three days.  





On Wed, Apr 19, 2017 11:46 AM, Omar Diab notifications@github.com  wrote:
Maybe in the future we can auto generate this stuff from the prop types, but for
now this is great.

**Comment by osdiab** [comment]
Btw do you want to rewrite the README text itself? So it doesn't contain duplicate docs?

**Comment by CarlNelson** [comment]
Yes, I should.
Carl NelsonDesign Lead, Cleverm |718.404.5914
w |https://clever.com
Sent with Mixmax  





On Wed, Apr 19, 2017 11:47 AM, Omar Diab notifications@github.com  wrote:
Btw do you want to rewrite the README text itself? So it doesn't contain
duplicate docs?

**Pull request merged**
