### PR TITLE
disabled Select2 state

### PR DESCRIPTION
**Pull request by johnhuangclever**
**Overview:**
Support optional and disabled requirements for Select2

**Screenshots/GIFs:**

https://user-images.githubusercontent.com/13126257/118107230-5a363b00-b393-11eb-986a-1aaca0866511.mov

**Testing:**

- [ ] Unit tests
- Manual tests:
  - [ ] Chrome
  - [ ] Safari
  - [ ] IE11

**Roll Out:**

- Before merging:
  - [ ] Updated docs
  - [ ] Bumped version in `package.json`
    - Breaking change?
      - If it is a beta component run `npm version minor`
      - If the component is not in beta run `npm version major`
    - New component or backward-compatible component feature change? Run `npm version minor`
    - Only changing documentation? All good. Skip this step.
  - After creating a new component, make sure to add it to the Components List in `ComponentsView.jsx`. To do so:
    - [ ] Add a screenshot of the component in `docs/assets/img` with the format `<COMPONENT URL LINK>.png`
- After merging:
  - [ ] Deployed updated docs (`make deploy-docs`)
  - [ ] Posted in #eng if I made a breaking change to a beta component

### CODE REVIEW

**Comment by ashleyqw** [comment]
Thanks for doing this so quickly John! Can we make it gray out when it's disabled so it's a little clearer that it's disabled without the label? Like this on Select

Screen Shot 2021-05-13 at 6 20 05 AM

**Comment by ashleyqw** [comment]
Also it won't actually have the label that says "disabled" right? If `hideLabel` is on?

**Comment by johnhuangclever** [comment]
The requirement is always visible as per the dewey 2.0 component designs. See TextInput2
image

From what I understand, the text was added to be more visually obvious that the component was disabled over any color indication

**Comment by johnhuangclever** [comment]
I'm happy to have a discussion with whoever designer/pm wants to use this in appstore

**Review by ashleyqw — APPROVED** [review]
Thanks John, LGTM!

**Pull request merged**
