### PR TITLE
Add documentation routing and display framework.

### PR DESCRIPTION
**Pull request by kofi-clever**
- Add documentation routing and display framework - https://github.com/Clever/components/commit/860a19e053ace37828fa2dbd40d5ccc861fcf8c9
- Port over existing live examples to new framework - https://github.com/Clever/components/commit/3ce241252688c83659e3df428f7ee5a2ed5913c6

design-system-docs

**Tested:**
- [x] Chrome
- [x] FF
- [ ] Safari
- [ ] IE10

Safari & IE10 currently broken due to a dependency written in ES6 syntax. Tracking it down to add it to our compilation step.

### CODE REVIEW

**Comment by samfishman** [comment]
Does Clever not ❤️ our design system??

**Comment by CarlNelson** [comment]
Why is there no dancing badger emoji on github. This is awesome, thanks @kofi-clever

**Comment by mischelle-m** [comment]
I'm just here to drop my jaw :jawdropped:

**Comment by osdiab** [comment]
Looks great to me so far! :shipit:

**Comment by kofi-clever** [comment]
k, fixed the Safari/IE issue. a library i added for stripping indentation was using ES6 syntax. since we don't include node_modules when downcompiling, just added inline logic for fixing the indentation and removed the library.

thanks a ton for reviewing! this was a big one.

will be following up with cleanup for the components missing code samples later, and will work with @CarlNelson to fill out the other pieces (intro, CSS pages, etc)

**Comment by kofi-clever** [comment]
will need to test this live to make sure navigation works as expected without the webpack-dev-server. if i run into any issues, will revert and revisit

**Pull request merged**
